micronaut:
  application:
    name: todo
  server:
    port: 8080
    cors:
      enabled: true
datasources:
  default:
    driver-class-name: ${DATASOURCES_DEFAULT_DRIVER:org.mariadb.jdbc.Driver}
    db-type: mariadb
    dialect: MYSQL
    jdbc-url: ${DATASOURCES_DEFAULT_URL:`jdbc:mariadb://localhost:3306/todo`}
    username: ${DATASOURCES_DEFAULT_USER:root}
    password: ${DATASOURCES_DEFAULT_PASSWORD:Password123!}
netty:
  default:
    allocator:
      max-order: 3
liquibase:
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.yml